### ISSUE TITLE
about status.json

### ISSUE THREAD

**Issue by ysymyth** [bootphon/intphys#10]
For objects and occluders respectively, what do the 6 descriptive numbers mean in status.json?

**Comment by mmmaat** [comment]
Hi,
Are you talking about the intphys-1.0 video (downloaded on intphys.com) ?
In that case the six numbers are **x y z rot_y rot_z rot_x**, position in meters and rotation in degrees.

**Comment by mmmaat** [comment]
Note this is **rot_y rot_z rot_x** and not **rot_x rot_y rot_z** (this was a bug we fixed for intphys-2.0)

**Comment by ysymyth** [comment]
thanks
