### ISSUE TITLE
Camera calibration 

### ISSUE THREAD

**Issue by pemami4911** [bootphon/intphys#9]
I'm trying to convert the RGB + depth data to point cloud, and I need to know the horizontal and vertical camera field of view. I'm unfamiliar with UE4 - is this something you can quickly determine and post here?

Thanks in advance

**Comment by mmmaat** [comment]
The camera FOV is set to 90 degrees (horizontal and vertical), with a perspective projection. See https://github.com/bootphon/intphys/blob/dbb53ca4a96000e35ca00c306d8176df7e7ba70d/Content/Scripts/actors/parameters.py#L9-L14

**Comment by pemami4911** [comment]
Thank you! I think it's working. Here's a sample: 
![047](https://user-images.githubusercontent.com/6277085/41438604-d1292ec8-6ff5-11e8-9f80-53234f20fd43.png)
I tried converting the depth of the sky from 0 to 255 and it seems to have helped the quality.

**Comment by mmmaat** [comment]
Great :)
